### ISSUE TITLE
fuzzy images

### ISSUE THREAD

**Issue by JeffreyMJohnson** [TeamQuestionIt/FinalProject#18]
sprites are all grainy and fuzzy in web build only. compression prob?

**Comment by QuinnJMosher** [comment]
That should be because it is Unity's "Fast" build, the final build should not have this problem. (This is mentioned in the build notes)

**Comment by JeffreyMJohnson** [comment]
it is not the build type. it is prob in web and webgl even with high quality build.  needs investigation.
