### ISSUE TITLE
WebGL : Title does not fit in screen space

### ISSUE THREAD

**Issue by Aidonis** [TeamQuestionIt/FinalProject#20]
Web build found @ http://jeffreymjohnson.github.io/QItUp/index.html

http://gyazo.com/54bc5888e330a259773195d8277b7d16

**Comment by Aidonis** [comment]
Seems like this is part of the camera issue #14, once in game the player can walk out of the visible screen space by heading left.

**Comment by QuinnJMosher** [comment]
fixed with the final builds
