### ISSUE TITLE
WebGL : Player HUD not updating

### ISSUE THREAD

**Issue by Aidonis** [TeamQuestionIt/FinalProject#21]
Chrome WebGL Build
@ http://jeffreymjohnson.github.io/QItUp/index.html

Player HUD does not seem to update.
HP / Lives / Orange Meter

**Comment by QuinnJMosher** [comment]
terry says that the problem is that we are using the webgl version

**Comment by Aidonis** [comment]
butts

On Mon, Jun 8, 2015 at 10:32 AM, QuinnJMosher notifications@github.com
wrote:

> Closed #21 https://github.com/TeamQuestionIt/FinalProject/issues/21.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TeamQuestionIt/FinalProject/issues/21#event-325517511
> .

## 

Thanks,
Aidan N.
