### ISSUE TITLE
Monster area restrictions and aggro triggers not playing nice together

### ISSUE THREAD

**Issue by BryceX** [TeamQuestionIt/FinalProject#3]
If the player is within the sight range of the monster and also behind an edge collider, the sight range overrides the edge collider restriction and causes it to flip back and forth quickly while moving past the collider.  As long as the enemies aren't shown flipping direction when they pass through an edge collider, it should be fine.

**Comment by JeffreyMJohnson** [comment]
Can't see this. Come show me the repo.
